config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  # Registration page and create action
  get 'register', to: 'player#new'
  post 'register', to: 'player#create'
  
  # Players history page
  get 'player_history', to: 'player#show'
  
  # Login routes and logout rout
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  # Some trivia session routes - allowing you to join next available, create auto game, custom game, and view the game page
  get '/trivia_session/any', to: 'trivia_session#join_any'
  get 'trivia_session/new'
  get 'trivia_session/create'
  get 'trivia_session/show'
  
  get 'new_custom', to: 'trivia_session#new_custom'
  post 'create_custom', to: 'trivia_session#create_custom'
 
  # Answer submission route in-game
  post '/submit_answer', to: 'player_answer#create'

  get 'pages/home'
end

app/models/trivia_session.rb
class TriviaSession < ApplicationRecord
    belongs_to :player
    belongs_to :trivia_session_state
    has_many :trivia_session_questions
    validates :name, presence: true, length: {minimum: 5, maximum: 100}
end

app/controllers/trivia_session_controller.rb
class TriviaSessionController < ApplicationController
  ###
  # @description: Displays the page for a new game
  # @return {any}: nil
  ###  
  def new
    if !logged_in?
      flash[:warning] = "You must be signed in to create or join trivia sessions."
      redirect_to(register_path)
    end
  end

  ###
  # @description: Default create action - creates a new auto-trivia session using the default number of min players, and a timestamp in the name
  # @return {any}: nil
  ###
  def create
    if !logged_in?
      flash[:warning] = "You must be signed in to create or join trivia sessions."
      redirect_to(register_path)
      return
    end
    # Auto create test
    @trivia_session = TriviaSession.create(player: current_user, trivia_session_state: TriviaSessionState.find_by(name: "Pending"),
                                           name: "Auto-Trivia " + Time.now.getutc.to_s.gsub(" UTC", ""))
    flash[:success] = "Created new auto-trivia game!"
    redirect_to(trivia_session_show_path(id: @trivia_session.id))
  end

  ###
  # @description: Creates a new custom game from for parameters, allowing the user to name the game and set minimum players
  # @return {any}: nil
  ###  
  def create_custom
    if !logged_in?
      flash[:warning] = "You must be signed in to create or join trivia sessions."
      redirect_to(register_path)
    end
    # Auto create test
    @trivia_session = TriviaSession.create(player: current_user, trivia_session_state: TriviaSessionState.find_by(name: "Pending"),
                                           name: params[:name], min_players: params[:min_players])
    flash[:success] = "Created new custom trivia game!"
    redirect_to(trivia_session_show_path(id: @trivia_session.id))
  end

  ###
  # @description: Displays the page for the new custom game
  # @return {any}: nil
  ###  
  def new_custom
    if !logged_in?
      flash[:warning] = "You must be signed in to create or join trivia sessions."
      redirect_to(register_path)
    end
  end

  ###
  # @description: Looks for the latest pending game that has already been created. If there is a pending game, we join it.
  #               If not, we create a new game with the default # of minimum players.
  # @return {any}: nil
  ###  
  def join_any
    if !logged_in?
      flash[:warning] = "You must be signed in to create or join trivia sessions."
      redirect_to(register_path)
    end
    pending_sessions = TriviaSession.where(trivia_session_state: TriviaSessionState.find_by(name: "Pending"))
    if !pending_sessions.any?
      redirect_to(trivia_session_create_path, is_auto: true)
    else
      # Join the most populated one
      pending_sessions = pending_sessions.order("created_at DESC")
      redirect_to(trivia_session_show_path(id: pending_sessions.first.id))
    end
  end

  ###
  # @description: Shows the page for a trivia session - this is the game-page.
  # @return {any}: nil
  ###  
  def show
    @trivia_session = TriviaSession.find_by(id: params[:id])
  end
end

app/helpers/trivia_session_helper.rb
module TriviaSessionHelper
end

app/views/trivia_session/new_custom.html.erb
<%= render "shared/simple_title", title: "New Custom" %>

<script>
$(document).ready(function() {
    // Quick "validation" to make sure we have given the game some sort of name
    $('#custom-form').submit(function() {  
        if ($('#game-name').val() == "") {
            alert("You must name your trivia game.");
            return false;
        }
        // Also make sure we are not starting a game for 0 people, and well max it out at 5k for now.
        // This is pretty arbitrary, but given were deploying on free heroku, probably more than enough
        if ($('#min-players').val() <= 0 || $('#min-players').val() > 5000) {
            alert("You can only have between 1 - 5,000 players");
            return false;
        }
    });

    return;
});


</script>

<div class="row">
    <div class="well col-lg-6 col-md-6 col-sm-6 col-sm-offset-3 col-md-offset-3 col-lg-offset-3">
        <%= form_tag(create_custom_path, id: "custom-form") do %>
            <%= label_tag(:name, "Game Name:") %>
            <%= text_field_tag(:name, "", id: "game-name") %>

            <%= label_tag(:min_players, "# Players To Start:") %>
            <%= number_field_tag(:min_players, 5, id: "min-players") %>

            <%= submit_tag("Create", class: "btn btn-success") %>

        <% end %>
        <br>
    </div>
</div>

app/views/trivia_session/show.html.erb
<div class="trivia-session-id-embed" id="ab-session-id" data-trivia-session-id="<%= @trivia_session != nil ? @trivia_session.id : 0 %>">
</div>
<div class="trivia-session-id-embed" id="ab-player-id" data-trivia-player-id="<%= current_user != nil ? current_user.id : 0 %>">
</div>

<%= javascript_pack_tag 'custom/trivia_session', 'data-turbolinks-track': 'reload' %>

<!-- I know this is awful and ugly but i can NOT get webpacker to work here... -->
<!-- Even in the webconsole i can see the file imported and my functions but it wont call them -->
<script>
    function disableForm() {
        $("#answer-form-fields").attr("disabled", "disabled");
    };
    $(document).ready(function (e) {
        $("#answer-form").submit(function (e2) {    
            console.log(e2.originalEvent.submitter.id);
            $(`#${e2.originalEvent.submitter.id}`).addClass("active");
            disableForm();
        });
    });
</script>

<!-- Side-bar section that shows how many players we started with, how many remain, and what # of question this is -->
<div class="container">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
            <div class="well">
                <small>
                    <table class="t-info-table">
                        <tr>
                            <td><strong>Min Players:<strong></td>
                            <td><span class="tsd-min-player-count"><%= @trivia_session != nil ? @trivia_session.min_players : 0 %></span></td>
                        </tr>
                        <tr>
                            <td><strong>Remaining:<strong></td>
                            <td><span class="tsd-current-player-count">1</span></td>
                        </tr>
                        <tr>
                            <td><strong>Question:<strong></td>
                            <td><span class="tsd-question-index">0</span></td>
                        </tr>
                    </table>
                </small>                
            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-9-2 col-xs-9">
            <div class="well">

                <!-- DIV when waiting for enough players to start -->
                <div class="contianer center" id="tse-pending-min-players-area">
                    <h3>Waiting for players...</h3>
                    <small>Your session will start soon</small>
                    <h5><span class="tsd-current-player-count">1</span> / <span class="tsd-min-player-count"><%= @trivia_session != nil ? @trivia_session.min_players : 0 %></span><h5>
                </div>

                <!-- DIV when timer countdown to start -->
                <div class="contianer center ab-hidden" id="tse-session-start-counter-area">
                    <h3>Game Starting In <span class="countdown-timer"></span></h3>
                    <small>Prepare for trivial battle!</small>
                </div>

                <!-- DIV when questions come through -->
                <div class="panel panel-warning ab-hidden" id="tse-question-area">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong id="question-text">Which NHL team won the Stanley Cup in the 2019-2020 season played in a bubble due to the Covid-19 pandemic?</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <h5 class="pull-right ab-timer-pad-right"><strong>Time Remaining: </strong><span class="countdown-timer"></span></h5>
                        </div>
                        <div class="list-group">

                            <!-- Answers are a form -->
                            <%= form_tag(submit_answer_path, id: "answer-form", remote: true) do %>
                                <fieldset id="answer-form-fields">
                                    <%= button_tag "Answer 1", name: "answer_id", class: "list-group-item list-group-item-action", id: "answer-1", type: "submit", value: 1 %>
                                    <%= button_tag "Answer 2", name: "answer_id", class: "list-group-item list-group-item-action", id: "answer-2", type: "submit", value: 2 %>
                                    <%= button_tag "Answer 3", name: "answer_id", class: "list-group-item list-group-item-action", id: "answer-3", type: "submit", value: 3 %>
                                    <%= button_tag "Asnwer 4", name: "answer_id", class: "list-group-item list-group-item-action", id: "answer-4", type: "submit", value: 4 %>
                                </fieldset>
                                <%= text_field_tag "player_id", current_user != nil ? current_user.id : 0, class: "ab-hidden", id: "form-player-id" %>
                                <%= text_field_tag "trivia_session_id", @trivia_session != nil ? @trivia_session.id : 0, class: "ab-hidden", id: "form-trivia-session-id" %>
                                <%= text_field_tag "question_id", "-1", class: "ab-hidden", id: "form-trivia-question-id" %>
                            <% end %>                            
                        </div>
                    </div>
                </div>  

                <!-- DIV ANswer review area - if you get eliminated, also provides a button to return home -->
                <div class="contianer center ab-hidden" id="tse-review-area">
                    <div class="row">
                        <h5 class="pull-right ab-timer-pad-right"><strong>Time Remaining: </strong><span class="countdown-timer"></span></h5>
                    </div>
                    <!-- Shows as Correct or Eliminated -->
                    <h2 id="this-players-result">Correct!</h2>
                    <div class="list-group">
                        <div class="list-group-item">
                            <strong><span id="result-answer-1-text"><strong>Answer 1: </strong></span><span class="ab-nudge-right" id="result-answer-1-count"></span>
                        </div>
                        <div class="list-group-item">
                            <strong><span id="result-answer-2-text"><strong>Answer 1: </strong></span><span class="ab-nudge-right" id="result-answer-2-count"></span>
                        </div>
                        <div class="list-group-item">
                            <strong><span id="result-answer-3-text"><strong>Answer 1: </strong></span><span class="ab-nudge-right" id="result-answer-3-count"></span>
                        </div>
                        <div class="list-group-item">
                            <strong><span id="result-answer-4-text"><strong>Answer 1: </strong></span><span class="ab-nudge-right" id="result-answer-4-count"></span>
                        </div>   
                    </div>      
                    <!-- When a player gets eliminated, this gets shown -->   
                    <%= link_to "Return Home", root_path, class: "btn btn-default btn-danger ab-hidden", id: "eliminated-return-button" %>        
                </div>

                <!-- DIV Victory message - once a player has won, they can see this part -->
                <div class="contianer center ab-hidden" id="tse-victors-circle">
                    <div class="alert alert-success" role="alert">
                        <h4 class="alert-heading">Victory!</h4>
                        <p>Congratulations! You have bested all of your oponnents in trivial warfare. Bragging rights are yours, as is our first place prize! Which is unfortunately nothing, but its all yours!</p>
                        <hr>
                        <p class="mb-0">Dont worry, all the losers had to donate 5$ to us, so youre still ahead.</p>
                        <%= link_to "Return Home", root_path, class: "btn btn-default btn-success" %>
                    </div>
                </div>

                <!-- DIV Eliminated players trying to rejoin -->
                <div class="contianer center ab-hidden" id="tse-eliminated-block">
                    <div class="alert alert-danger" role="alert">
                        <h4 class="alert-heading">Cheater!</h4>
                        <p>You were already eliminated from this session. You cant just slide back in here pretending nothing ever happened! Go home!</p>
                        <hr>
                        <p class="mb-0">Go on, Get.</p>
                        <%= link_to "Return Home", root_path, class: "btn btn-default btn-danger" %>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>