config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  # Registration page and create action
  get 'register', to: 'player#new'
  post 'register', to: 'player#create'
  
  # Players history page
  get 'player_history', to: 'player#show'
  
  # Login routes and logout rout
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  # Some trivia session routes - allowing you to join next available, create auto game, custom game, and view the game page
  get '/trivia_session/any', to: 'trivia_session#join_any'
  get 'trivia_session/new'
  get 'trivia_session/create'
  get 'trivia_session/show'
  
  get 'new_custom', to: 'trivia_session#new_custom'
  post 'create_custom', to: 'trivia_session#create_custom'
 
  # Answer submission route in-game
  post '/submit_answer', to: 'player_answer#create'

  get 'pages/home'
end

app/models/answer.rb
class Answer < ApplicationRecord
    # I could have done a questions table, answers table, then a question_answers table
    # and associated them with a has_many through, but since the answers are pretty
    # specific to the question its not really worth it.
    # Just wanted to note the thought
    belongs_to :question
    validates :answer, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
    validates :display_name, presence: true, length: {minimum: 3, maximum: 50 }
    
    before_save { self.email = email.downcase }

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {minimum: 5, maximum: 105 },
                uniqueness: { case_sensitive: false },
                format: { with: VALID_EMAIL_REGEX }    
end

app/models/player_answer.rb
class PlayerAnswer < ApplicationRecord
    belongs_to :player
    belongs_to :trivia_session
    belongs_to :answer
    belongs_to :question
end

app/models/player_trivia_session_record.rb
class PlayerTriviaSessionRecord < ApplicationRecord
    belongs_to :player
    belongs_to :trivia_session    
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers
    belongs_to :question_category
    validates :question, presence: true, length: {minimum: 10, maximum: 200}
end

app/models/question_category.rb
class QuestionCategory < ApplicationRecord
    has_many :questions
    validates :name, presence: true, length: {minimum: 3, maximum: 20}
end

app/models/trivia_session.rb
class TriviaSession < ApplicationRecord
    belongs_to :player
    belongs_to :trivia_session_state
    has_many :trivia_session_questions
    validates :name, presence: true, length: {minimum: 5, maximum: 100}
end

app/models/trivia_session_question.rb
class TriviaSessionQuestion < ApplicationRecord
    belongs_to :trivia_session
    belongs_to :question
    validates :question_index, presence: true, :numericality => {:only_integer => true}
    # We want to be sure that each trivia session has a running index, or at the very least,
    # no index duplicates - otherwise we might show different questions to some users
    validates_uniqueness_of :question_index, scope: :trivia_session_id
end

app/models/trivia_session_state.rb
class TriviaSessionState < ApplicationRecord
    has_many :trivia_sessions
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user()
        # Not exactly memoizing... but if undefined, do right side, otherwise dont (minus some nuances)
        @current_user ||= Player.find(session[:player_id]) if session[:player_id]
    end

    def logged_in?()
        # Basically a bool cast
        !!current_user()
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  # I could have used has_secure_password on the player model (or a better system entirely)
  # and then done an authenticate here, but I think for the purposes of this demo, noting
  # that it can be done is enough. Not an impressive enough thing to add to spend the time, or
  # your time to think up and use passwords
  def create
    email = params[:email].downcase
    player = Player.find_by(email: email)
    if player
      session[:player_id] = player.id
      flash[:success] = "Logged in as \"#{player.display_name}\""
      redirect_to(root_path)
    else
      flash[:danger] = "No player currently registered with the email: #{email}."
      # TODO: Redirect to sign up
      redirect_to(root_path)
    end
  end

  # Keeping things simple for this example
  def destroy
    session[:player_id] = nil
    flash[:success] = "You have been signed out."
    redirect_to(root_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  ###
  # @description: displays the new player page (register form)
  # @return {any}: nil
  ###
  def new
    @player = Player.new()
  end

  ###
  # @description: Creates a new player using values from the register form, assuming they were entered appropriately
  # @return {any}: nil
  ###
  def create
    @player = Player.new(player_params())
    if @player.save
      flash[:success] = "Your account has been created!"
      session[:player_id] = @player.id
      redirect_to(root_path)
    else
      render(:new)
    end
  end
  
  ###
  # @description: Displays a player, this will be their history page (wins and losses)
  # @return {any}: nil
  ###
  def show
    if !logged_in?
      redirect_to(login_path)      
    end
    @player = current_user() 
  end

  
  private
    ###
    # @description: helper to whitelist form fields
    ###
    def player_params
      params.require(:player).permit(:email, :display_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/player_answer_helper.rb
module PlayerAnswerHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/trivia_session_helper.rb
module TriviaSessionHelper
end

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <%= link_to image_tag("abtrivia_logo_02.JPG", border: 0, height: 50), {action: 'home', controller: 'pages'}, class: 'dock-item', id: "logo" %>

        <% if logged_in? %>
            <!-- If logged in, view my history link -->
            <div class="nav_item">
                <%= link_to "My History", player_history_path, class: "btn btn-default btn-ab-nav" %>
            </div>

            <!-- Username dropdown menu -->
            <ul class="nav_item pull-right no-disc-list">
                <li class="dropdown">
                    <%= link_to("#", class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown") do %>
                        <%= current_user().display_name %> <b class="caret"></b>
                    <% end %>
                    <ul class="dropdown-menu">
                        <li><%= link_to("My History", player_history_path) %></li>
                        <li class="divider"></li>
                        <li><%= link_to("Logout", logout_path) %></li>
                    </ul>
                </li>
            </ul>

        <% else %>
            <!-- Register and login links-->
            <div class="nav_item pull-right">
                <%= link_to "Register", register_path, class: "btn btn-default btn-ab-nav" %>
                <%= link_to "Login", login_path, class: "btn btn-default btn-success" %>
            </div>
        <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABTrivia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/flash_alerts" %>
    <%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-12">
        <div class="well container">

            <!-- When user is logged in -->
            <% if logged_in? %>
                <p><h3 class="center">Welcome, <%= current_user.display_name %></h3></p>
                <hr>
                <div class="center">
                    <table class="buttons">
                        <tr>
                            <td><%= link_to "Join Next Game", trivia_session_any_path, class: "btn btn-default btn-ab-nav" %></td>
                        </tr>
                        <tr>
                            <td><%= link_to "Create New Custom", new_custom_path, class: "btn btn-default btn-ab-nav" %></td>
                        </tr>
                    </table>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <footer><small>You should definitely hire me!</small></footer>
                </div>
            <% else %>
                <p><h3 class="center">Get Started</h3></p>
                <hr>
                <div class="center">
                    <h4>To hop into a trivia game, all you need to do is register with a display name and email address!</h5>
                    <br>
                    <%= link_to "Register", register_path, class: "btn btn-default btn-ab-nav" %>
                    <hr>
                    <br>
                    <br>
                    <strong>Trivia categories include:</strong></h6>
                    <br>
                    <br>
                    <div class="container ab-tight">
                        <small>
                        <ul class="disc-inside">
                            <% QuestionCategory.all.order(:name).each do |cat| %>
                                <li><%= cat.name %></li>
                            <% end %>
                        </ul>
                    </small>
                    </div>
                    <br>
                    <br>
                    <br>
                    <footer><small>You should definitely hire me!</small></footer>
                </div>
            <% end %>
         </div>
    </div>
</div>

app/views/shared/_flash_alerts.html.erb
<div class="center">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
            <% flash.each do |message_type, message| %>
                <div class="alert alert-dismissible fade in alert-<%= message_type %>">
                    <%= message %>
                    <a class="close" data-dismiss="alert">&#215;</a>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_form_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="alert alert-danger col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
            <h5>The following errors were found:</h5>
            <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/shared/_simple_title.html.erb
<p>
    <h1 class="ab-content-title"><%= (defined?(title) == nil ? "Unknown" : title ) %></h1>
    <hr>
    <br>
</p>